[build]
  command = "npm run build"
  publish = ".next"

# Production-specific settings
[context.production]
  command = "npm run build"
  publish = ".next"

# Staging-specific settings
[context.staging]
  command = "npm run build"
  publish = ".next"

# Deploy previews (pull request builds)
[context.deploy-preview]
  command = "npm run build"
  publish = ".next"

# Branch-specific deploy settings
[context.branch-deploy]
  command = "npm run build"
  publish = ".next"
