[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "18"
  NEXT_PUBLIC_SANITY_PROJECT_ID = "1gxdk71x"
  NEXT_PUBLIC_SANITY_DATASET = "production"
  NEXT_PUBLIC_SANITY_API_VERSION = "2024-03-13"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max_old_space_size=4096"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

[[plugins]]
package = "@netlify/plugin-nextjs"
  [plugins.inputs]
  splitNextBuild = true
  experimentalBundling = true

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/studio/*"
  to = "https://all7z.sanity.studio/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200