[build]
  command = """
    npm ci && \
    cd fresh_sanity_studio && \
    NODE_ENV=development npm ci && \
    npm install postcss autoprefixer tailwindcss --save-dev && \
    NODE_ENV=production SANITY_STUDIO_DATASET=production DISABLE_ESLINT_PLUGIN=true npm run build && \
    cd .. && \
    NODE_ENV=production NEXT_PUBLIC_ENVIRONMENT=production SANITY_STUDIO_DATASET=production npm run build:production
  """
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NETLIFY = "true"
  NEXT_PUBLIC_NETLIFY = "true"
  NEXT_PUBLIC_SANITY_STUDIO_URL = "https://all7z.sanity.studio"
  SANITY_STUDIO_PATH = "fresh_sanity_studio"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20.11.1"
  NPM_FLAGS = "--no-audit --no-fund"
  USE_PNPM = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Keep all your existing redirects
[[redirects]]
  from = "/api/form-submission"
  to = "/.netlify/functions/form-submission"
  status = 200
  force = true

        [[redirects]]
          from = "/api/music-metadata"
  to = "/.netlify/functions/music-metadata"
  status = 200
  force = true

[[redirects]]
  from = "/studio/*"
  to = "/studio/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Keep all your environment-specific configurations
[context.production]
  command = "npm install && cd fresh_sanity_studio && npm install && npm run build && cd .. && npm run build:production"
  publish = ".next"
  [context.production.environment]
    NEXT_PUBLIC_ENVIRONMENT = "production"
    SANITY_STUDIO_DATASET = "production"
    NODE_ENV = "production"
    NEXT_PUBLIC_SANITY_DATASET = "production"
    NEXT_PUBLIC_SANITY_PROJECT_ID = "1gxdk71x"
    NEXT_PUBLIC_NETLIFY = "true"
    NEXT_PUBLIC_SANITY_STUDIO_URL = "https://all7z.sanity.studio"
    NEXT_PUBLIC_SITE_URL = "https://all7z.com"
    SANITY_AUTH_TOKEN = "env(SANITY_AUTH_TOKEN)"
    SANITY_STUDIO_API_TOKEN = "env(SANITY_STUDIO_API_TOKEN)"
    NEXT_PUBLIC_SANITY_TOKEN = "env(NEXT_PUBLIC_SANITY_TOKEN)"
    STRIPE_SECRET_KEY = "env(STRIPE_SECRET_KEY)"
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "env(NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY)"
    SANITY_PREVIEW_TOKEN = "env(SANITY_PREVIEW_TOKEN)"

[context.staging]
  command = "npm run build:staging"
  publish = ".next"
  [context.staging.environment]
    NEXT_PUBLIC_ENVIRONMENT = "staging"
    NEXT_PUBLIC_SANITY_DATASET = "staging"
    NEXT_PUBLIC_SANITY_PROJECT_ID = "1gxdk71x"
    NEXT_PUBLIC_NETLIFY = "true"
    NEXT_PUBLIC_SANITY_STUDIO_URL = "https://all7z.sanity.studio"
    NEXT_PUBLIC_SITE_URL = "https://staging.all7z.com"

[context.deploy-preview]
  command = "npm run build"
  publish = ".next"
  [context.deploy-preview.environment]
    NEXT_PUBLIC_SANITY_STUDIO_URL = "https://deploy-preview-${REVIEW_ID}--stak-app.netlify.app/studio"
    NEXT_PUBLIC_SITE_URL = "https://deploy-preview-${REVIEW_ID}--stak-app.netlify.app"

[context.branch-deploy]
  command = "npm run build"
  publish = ".next"
  [context.branch-deploy.environment]
    NEXT_PUBLIC_SANITY_STUDIO_URL = "https://branch-${BRANCH}--stak-app.netlify.app/studio"
    NEXT_PUBLIC_SITE_URL = "https://branch-${BRANCH}--stak-app.netlify.app"

# Keep your existing processing settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Keep your existing functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
# Add form handling function
[functions.form-submission]
  included_files = ["lib/formHandling.js"]

# Keep your existing function configurations
[functions.extract-album-durations]
  included_files = ["lib/extractDurations.js"]

[functions.music-metadata]
  included_files = ["lib/spotify.js"]

[functions.fetchBatchSpotifyMetadata]
  included_files = ["lib/spotify.js"]

# Keep your existing dev settings
[dev]
  command = "cross-env NODE_ENV=development SANITY_STUDIO_API_TOKEN=$SANITY_AUTH_TOKEN next dev"
  targetPort = 3000
  port = 8888
  publish = "out"
  framework = "next"

[dev.environment]
  NEXT_PUBLIC_NETLIFY = "true"
  SPOTIFY_CLIENT_ID = "env(SPOTIFY_CLIENT_ID)"
  SPOTIFY_CLIENT_SECRET = "env(SPOTIFY_CLIENT_SECRET)"
  SANITY_STUDIO_PATH = "fresh_sanity_studio"
  NEXT_PUBLIC_SANITY_STUDIO_URL = "https://all7z.sanity.studio"
  SANITY_STUDIO_API_TOKEN = "env(SANITY_STUDIO_API_TOKEN)"

