[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "18"

# Staging-specific settings
[context.staging]
  command = "npm run build:staging"
  [context.staging.environment]
    NEXT_PUBLIC_ENVIRONMENT = "staging"
    NEXT_PUBLIC_SANITY_DATASET = "staging"
    NEXT_PUBLIC_SANITY_PROJECT_ID = "1gxdk71x"
    NEXT_PUBLIC_NETLIFY = "true"
    NODE_ENV = "development"

# Production-specific settings
[context.production]
  command = "npm run build:production"
  [context.production.environment]
    NEXT_PUBLIC_ENVIRONMENT = "production"
    NEXT_PUBLIC_SANITY_DATASET = "production"
    NEXT_PUBLIC_SANITY_PROJECT_ID = "1gxdk71x"
    NEXT_PUBLIC_NETLIFY = "true"
    NODE_ENV = "production"

[[plugins]]
package = "@netlify/plugin-nextjs"
  [plugins.inputs]
  splitNextBuild = true
  experimentalBundling = true

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/studio/*"
  to = "https://all7z.sanity.studio/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200