[build]
  command = "npm run build"
  publish = ".next"

# Production-specific settings
[context.production]
  command = "npm run build"
  publish = ".next"
  [context.production.environment]
    NEXT_PUBLIC_ENVIRONMENT = "production"
    NEXT_PUBLIC_SANITY_DATASET = "production"
    NEXT_PUBLIC_SANITY_PROJECT_ID = "1gxdk71x"
    NEXT_PUBLIC_SANITY_TOKEN = "env(NEXT_PUBLIC_SANITY_TOKEN)" # Ensure this is set in the Netlify dashboard

# Staging-specific settings
[context.staging]
  command = "npm run build"
  publish = ".next"
  [context.staging.environment]
    NEXT_PUBLIC_ENVIRONMENT = "staging"
    NEXT_PUBLIC_SANITY_DATASET = "staging"
    NEXT_PUBLIC_SANITY_PROJECT_ID = "1gxdk71x"
    NEXT_PUBLIC_SANITY_TOKEN = "env(NEXT_STAGING_SANITY_TOKEN)" # Reference environment variable

# Deploy previews (pull request builds)
[context.deploy-preview]
  command = "npm run build"
  publish = ".next"

# Branch-specific deploy settings
[context.branch-deploy]
  command = "npm run build"
  publish = ".next"
